language: node
rvm:
  - '4'

env:
  global:
  - ENCRYPTION_LABEL: "3c823bf81e58"
  - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
  - TRIGGER_REPO_SLUG: "patternfly/patternfly-design"
  - TRIGGER_REPO_BRANCH: "master"

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD

script:
  - 'npm install'
  - './script/status.js'

after_success:
  - ./script/publish-ghpages.sh -t publish
